//! Make sure the ROM-derived `src/music/songs.rs` exists (writing a stub when it
//! doesn't) so `mod songs;` always compiles and rust-analyzer sees it.
//! `gen_music` overwrites the stub with the real songs. (The `note` const grid
//! is generated by the `lotw-music` crate's build.rs.)

const SONGS_STUB: &str = "\
//! Stub — run `cargo run --bin gen_music` to generate the real songs/SFX.
use lotw_music::{Song, Tok};
pub fn get(_: usize) -> Option<Song> { None }
pub fn sfx(_: usize) -> Option<Vec<Tok>> { None }
";

fn main() {
    println!("cargo::rerun-if-changed=src/music/songs.rs");
    let songs = std::path::Path::new("src/music/songs.rs");
    if !songs.exists() {
        let _ = std::fs::write(songs, SONGS_STUB);
    }
}
