//! Note symbols for the music DSL: pitch×value consts (`a3i`, `cs4qd`), rests
//! (`ri`, `rq`), the five channel commands, off-grid `raw`/`rest`, and `bar`
//! (end/loop). Import them all with `use crate::music::note::*;`.

#![allow(non_upper_case_globals)]

use super::{Note, Val};

// `<note><octave><value>` and `r<value>` consts — generated by build.rs (pure
// note math, no ROM data), e.g. `pub const a3i: Note = ...;`.
include!(concat!(env!("OUT_DIR"), "/note_consts.rs"));

/// The five channel commands (`0xFF id arg`).
pub const fn duty(arg: u8) -> Note {
    Note::Cmd { id: 0, arg }
}
pub const fn volume(arg: u8) -> Note {
    Note::Cmd { id: 1, arg }
}
pub const fn flags(arg: u8) -> Note {
    Note::Cmd { id: 2, arg }
}
pub const fn pitch(arg: u8) -> Note {
    Note::Cmd { id: 3, arg }
}
pub const fn sweep(arg: u8) -> Note {
    Note::Cmd { id: 4, arg }
}
/// A command by raw id (for ids outside the named five).
pub const fn cmd(id: u8, arg: u8) -> Note {
    Note::Cmd { id, arg }
}

/// An off-grid note: explicit pitch byte + tick count (for pitches/durations
/// that don't land on a named note value).
pub const fn raw(pitch: u8, ticks: u8) -> Note {
    Note::RawNote { pitch, ticks }
}
/// An off-grid rest of `ticks` frames.
pub const fn rest(ticks: u8) -> Note {
    Note::RawRest { ticks }
}

/// End of stream (the loop / stop point).
pub const bar: Note = Note::End;
