//! Note symbols for the music DSL: pitch×value consts (`a3i`, `cs4qd`), rests
//! (`ri`, `rq`), the five channel commands, off-grid `raw`/`rest`. Import them
//! all with `use lotw_music::note::*;`.

#![allow(non_upper_case_globals)]

use crate::Note;

// `<note><octave><value>`, `r<value>`, and `hit<value>` consts, each with a
// one-line doc — generated by the `note_consts!` proc macro (music-macros crate).
lotw_music_macros::note_consts!();

// The five channel commands (`0xFF id arg`), id 0..=4. Each emits one `Cmd`
// token that updates the channel's playback state until the next such command.

/// **Duty / instrument** (command 0). The argument's high nibble picks the pulse
/// **duty cycle** (the waveform timbre); the low nibble picks an envelope
/// "instrument" (a sustain/decay shape from the ROM's table). The most common
/// timbre setter — e.g. `duty(0x36)`.
pub const fn duty(arg: u8) -> Note {
    Note::Cmd { id: 0, arg }
}
/// **Volume** (command 1). Scales the channel's 0..15 envelope output: higher
/// `arg` is louder (mapped to an odd multiplier internally). Drop it for accents
/// and fades — see the [`volume!`](lotw_music_macros::volume) macro to step it
/// across a run of notes.
pub const fn volume(arg: u8) -> Note {
    Note::Cmd { id: 1, arg }
}
/// **Flags** (command 2). Overwrites the channel's raw duty/volume-flag byte
/// wholesale — the low-level form of [`duty`] for setting APU flag bits directly
/// (constant-volume vs envelope, length-counter halt, …).
pub const fn flags(arg: u8) -> Note {
    Note::Cmd { id: 2, arg }
}
/// **Pitch bend** (command 3). A fine offset subtracted from each note's
/// looked-up period, so a larger `arg` raises the pitch. Use the
/// [`pitch!`](lotw_music_macros::pitch) macro to bend across notes
/// (absolute or relative `+`/`-`).
pub const fn pitch(arg: u8) -> Note {
    Note::Cmd { id: 3, arg }
}
/// **Sweep / drum period** (command 4). On the pulse channels this is the APU
/// sweep-unit value (an automatic period glide). On the **noise** channel it
/// sets the drum period — i.e. which drum a following [`hit`] sounds.
pub const fn sweep(arg: u8) -> Note {
    Note::Cmd { id: 4, arg }
}
/// A command by raw id (for ids outside the named five). (`n` not `id`: `id`
/// is a note-value const — a dotted sixteenth.)
pub const fn cmd(n: u8, arg: u8) -> Note {
    Note::Cmd { id: n, arg }
}

/// An off-grid note: explicit pitch byte + tick count.
pub const fn raw(pitch: u8, ticks: u8) -> Note {
    Note::RawNote { pitch, ticks }
}
/// An off-grid rest of `ticks` frames.
pub const fn rest(ticks: u8) -> Note {
    Note::RawRest { ticks }
}
/// An off-grid noise drum hit of `ticks` frames (no pitch).
pub const fn hit(ticks: u8) -> Note {
    Note::RawHit { ticks }
}

/// Per-channel loop **override**: when this channel reaches its end it jumps back
/// **here**, regardless of the song-level loop. Normally a song loops via
/// `song(…).loop_from(n)` (all channels from section `n`); use this marker only
/// where one channel's loop doesn't sit on that shared boundary (e.g. song 12's
/// pulse2, an eighth-note off). Emits no bytes.
pub const loop_start: Note = Note::LoopStart;
/// Per-channel override marking a channel that does **not** loop. The song-level
/// `song(…).no_loop()` covers the usual one-shot; this is for the rare channel
/// that differs from its song's setting. Emits no bytes.
pub const no_loop: Note = Note::NoLoop;
