-- FCEUX execution trace driver for Legacy of the Wizard.
--
-- Inputs:
--   LOTW_TRACE_OUT_DIR   required output directory
--   LOTW_TRACE_LABELS    labels.txt generated by lotw_disasm
--   LOTW_TRACE_REPLAY    optional replay fixture path
--   LOTW_TRACE_FRAMES    frame count to run, default 180
--   LOTW_TRACE_LABEL_STATE_HIT_LIMIT  per-label state hits to capture, default 32
--   LOTW_TRACE_DONE      optional completion marker path

local out_dir = os.getenv("LOTW_TRACE_OUT_DIR")
local labels_path = os.getenv("LOTW_TRACE_LABELS")
local replay_path = os.getenv("LOTW_TRACE_REPLAY")
local done_path = os.getenv("LOTW_TRACE_DONE")
local max_frames = tonumber(os.getenv("LOTW_TRACE_FRAMES") or "180")
local label_state_hit_limit = tonumber(os.getenv("LOTW_TRACE_LABEL_STATE_HIT_LIMIT") or "32")

if not out_dir or out_dir == "" then
  error("LOTW_TRACE_OUT_DIR is required")
end

if not labels_path or labels_path == "" then
  error("LOTW_TRACE_LABELS is required")
end

if not max_frames or max_frames < 1 then
  error("LOTW_TRACE_FRAMES must be positive")
end

if not label_state_hit_limit or label_state_hit_limit < 1 then
  error("LOTW_TRACE_LABEL_STATE_HIT_LIMIT must be positive")
end

local register_execute = memory.registerexecute or memory.registerexec
if not register_execute then
  error("FCEUX memory.registerexecute/registerexec is unavailable")
end

local function split_words(line)
  local words = {}
  for word in string.gmatch(line, "%S+") do
    table.insert(words, word)
  end
  return words
end

local valid_buttons = {
  up = true,
  down = true,
  left = true,
  right = true,
  A = true,
  B = true,
  start = true,
  select = true,
}

local function parse_replay(path)
  local frames = {}
  local total = 0

  if not path or path == "" then
    return frames
  end

  local f = assert(io.open(path, "r"))
  for line in f:lines() do
    line = string.gsub(line, "#.*$", "")
    local words = split_words(line)

    if #words > 0 then
      if words[1] ~= "frame" then
        error("unknown replay directive: " .. words[1])
      end

      local count = tonumber(words[2])
      if not count or count < 1 then
        error("invalid replay frame count")
      end

      local buttons = {}
      for i = 3, #words do
        if not valid_buttons[words[i]] then
          error("unknown replay button: " .. words[i])
        end
        buttons[words[i]] = true
      end

      for _ = 1, count do
        total = total + 1
        frames[total] = buttons
      end
    end
  end
  f:close()

  return frames
end

local function write_file(path, data)
  local f = assert(io.open(path, "wb"))
  assert(f:write(data))
  assert(f:close())
end

local function get_register(names)
  if not memory.getregister then
    return nil
  end

  for _, name in ipairs(names) do
    local ok, value = pcall(memory.getregister, name)
    if ok and type(value) == "number" then
      return value
    end
  end

  return nil
end

local function get_cpu_state()
  return {
    pc = get_register({ "pc", "PC" }),
    a = get_register({ "a", "A" }),
    x = get_register({ "x", "X" }),
    y = get_register({ "y", "Y" }),
    p = get_register({ "p", "P", "flags", "FLAGS" }),
    s = get_register({ "s", "S", "sp", "SP" }),
  }
end

local function read_ram_hex()
  local chunks = {}
  for addr = 0, 0x7ff do
    chunks[#chunks + 1] = string.format("%02X", memory.readbyte(addr))
  end
  return table.concat(chunks)
end

local function fmt_reg(value, width)
  if value == nil then
    return "unknown"
  end
  return string.format("%0" .. tostring(width) .. "X", value)
end

local function get_cycle_count()
  if debugger and debugger.getcyclescount then
    local ok, value = pcall(debugger.getcyclescount)
    if ok and type(value) == "number" then
      return value
    end
  end

  return nil
end

local labels = {}
local vector_roles = {}

do
  local f = assert(io.open(labels_path, "r"))
  for line in f:lines() do
    local vector, label = string.match(line, "^(vector_%w+)=L_([0-9A-Fa-f]+)")
    if vector and label then
      local addr = tonumber(label, 16)
      vector_roles[addr] = vector_roles[addr] and (vector_roles[addr] .. "," .. vector) or vector
      labels[addr] = true
    else
      local target = string.match(line, "^L_([0-9A-Fa-f]+)")
      if target then
        labels[tonumber(target, 16)] = true
      end
    end
  end
  f:close()
end

local label_count = 0
for _ in pairs(labels) do
  label_count = label_count + 1
end

local prg_page_count = 16
local second_last_page = prg_page_count - 2
local last_page = prg_page_count - 1
local bank_select = 0
local prg_mode = 0
local bank_regs = {}
for i = 0, 7 do
  bank_regs[i] = nil
end

local mapper_writes = {}
local mapper_write_count = 0
local apu_writes = {}
local apu_write_count = 0
local ppu_writes = {}
local ppu_write_count = 0
local ppu_vram_writes = {}
local ppu_vram_write_count = 0
local oam_dma_writes = {}
local oam_dma_count = 0

local function normalize_page(page)
  if page == nil then
    return nil
  end
  return math.mod(page, prg_page_count)
end

local function map_prg_offset(addr)
  local page = nil

  if addr >= 0x8000 and addr < 0xa000 then
    if prg_mode == 0 then
      page = normalize_page(bank_regs[6])
    else
      page = second_last_page
    end
  elseif addr >= 0xa000 and addr < 0xc000 then
    page = normalize_page(bank_regs[7])
  elseif addr >= 0xc000 and addr < 0xe000 then
    if prg_mode == 0 then
      page = second_last_page
    else
      page = normalize_page(bank_regs[6])
    end
  elseif addr >= 0xe000 then
    page = last_page
  end

  if page == nil then
    return nil
  end

  return page * 0x2000 + math.mod(addr, 0x2000)
end

local frame = 0

local function record_mapper_write(addr, _, value)
  if addr == 0x8000 then
    bank_select = AND(value, 0x07)
    prg_mode = AND(value, 0x40) ~= 0 and 1 or 0
  elseif addr == 0x8001 then
    bank_regs[bank_select] = value
  end

  mapper_write_count = mapper_write_count + 1
  mapper_writes[#mapper_writes + 1] = string.format(
    "%d\t%04X\t%02X\tselect=%d\tprg_mode=%d\tr6=%s\tr7=%s\n",
    frame,
    addr,
    value,
    bank_select,
    prg_mode,
    bank_regs[6] == nil and "unknown" or string.format("%02X", bank_regs[6]),
    bank_regs[7] == nil and "unknown" or string.format("%02X", bank_regs[7]))
end

memory.registerwrite(0x8000, 1, record_mapper_write)
memory.registerwrite(0x8001, 1, record_mapper_write)

local function record_apu_write(addr, _, value)
  local cycle = get_cycle_count()
  apu_write_count = apu_write_count + 1
  apu_writes[#apu_writes + 1] = string.format(
    "%d\t%s\t%04X\t%02X\n",
    frame,
    cycle == nil and "unknown" or tostring(cycle),
    addr,
    value)
end

memory.registerwrite(0x4000, 0x14, record_apu_write)
memory.registerwrite(0x4015, 1, record_apu_write)
memory.registerwrite(0x4017, 1, record_apu_write)

local ppu_register_names = {
  [0x2000] = "PPUCTRL",
  [0x2001] = "PPUMASK",
  [0x2002] = "PPUSTATUS",
  [0x2003] = "OAMADDR",
  [0x2004] = "OAMDATA",
  [0x2005] = "PPUSCROLL",
  [0x2006] = "PPUADDR",
  [0x2007] = "PPUDATA",
  [0x4014] = "OAMDMA",
}

local ppu_ctrl = 0
local ppu_addr_latch = 0
local ppu_addr_high = 0
local ppu_vram_addr = 0

local function ppu_register_name(addr)
  if addr >= 0x2000 and addr < 0x4000 then
    return ppu_register_names[0x2000 + math.mod(addr, 8)]
  end

  return ppu_register_names[addr] or "unknown"
end

local function ppu_vram_region(addr)
  if addr < 0x2000 then
    return "pattern"
  elseif addr < 0x3f00 then
    return "nametable"
  elseif addr < 0x4000 then
    return "palette"
  end

  return "unknown"
end

local function record_ppu_vram_write(cycle, addr, value)
  ppu_vram_write_count = ppu_vram_write_count + 1
  ppu_vram_writes[#ppu_vram_writes + 1] = string.format(
    "%d\t%s\t%04X\t%s\t%02X\n",
    frame,
    cycle == nil and "unknown" or tostring(cycle),
    addr,
    ppu_vram_region(addr),
    value)
end

local function read_oam_dma_hex(page)
  local chunks = {}
  local base = page * 0x100
  for offset = 0, 0xff do
    chunks[#chunks + 1] = string.format("%02X", memory.readbyte(base + offset))
  end
  return table.concat(chunks)
end

local function record_oam_dma_write(cycle, page)
  oam_dma_count = oam_dma_count + 1
  oam_dma_writes[#oam_dma_writes + 1] = string.format(
    "%d\t%s\t%02X\t%s\n",
    frame,
    cycle == nil and "unknown" or tostring(cycle),
    page,
    read_oam_dma_hex(page))
end

local function record_ppu_write(addr, _, value)
  local cycle = get_cycle_count()
  local reg_addr = addr
  if addr >= 0x2000 and addr < 0x4000 then
    reg_addr = 0x2000 + math.mod(addr, 8)
  end

  ppu_write_count = ppu_write_count + 1
  ppu_writes[#ppu_writes + 1] = string.format(
    "%d\t%s\t%04X\t%s\t%02X\n",
    frame,
    cycle == nil and "unknown" or tostring(cycle),
    addr,
    ppu_register_name(addr),
    value)

  if reg_addr == 0x2000 then
    ppu_ctrl = value
  elseif reg_addr == 0x2005 then
    ppu_addr_latch = 1 - ppu_addr_latch
  elseif reg_addr == 0x2006 then
    if ppu_addr_latch == 0 then
      ppu_addr_high = value
      ppu_addr_latch = 1
    else
      ppu_vram_addr = AND(ppu_addr_high * 0x100 + value, 0x3fff)
      ppu_addr_latch = 0
    end
  elseif reg_addr == 0x2007 then
    record_ppu_vram_write(cycle, ppu_vram_addr, value)
    if AND(ppu_ctrl, 0x04) ~= 0 then
      ppu_vram_addr = AND(ppu_vram_addr + 32, 0x3fff)
    else
      ppu_vram_addr = AND(ppu_vram_addr + 1, 0x3fff)
    end
  elseif reg_addr == 0x4014 then
    record_oam_dma_write(cycle, value)
  end
end

memory.registerwrite(0x2000, 0x2000, record_ppu_write)
memory.registerwrite(0x4014, 1, record_ppu_write)

if memory.registerread then
  memory.registerread(0x2002, 1, function()
    ppu_addr_latch = 0
  end)
end

local executed = {}
local executed_count = 0
local label_state_hit_count = 0
local label_state_hit_rows = {
  "cpu_addr\tprg_offset\thit_ordinal\tframe\tpc\ta\tx\ty\tp\ts\tram_0000_07ff\n"
}

local function register_label(addr)
  register_execute(addr, function()
    local prg_offset = map_prg_offset(addr)
    local key = string.format("%04X:%s", addr, prg_offset == nil and "unknown" or string.format("%05X", prg_offset))
    local rec = executed[key]
    local state = nil
    local ram = nil

    if rec == nil then
      rec = {
        addr = addr,
        prg_offset = prg_offset,
        count = 0,
        first_frame = frame,
        role = vector_roles[addr] or "",
        state = nil,
        ram = nil,
      }
      executed[key] = rec
      executed_count = executed_count + 1
    end

    if rec.count < label_state_hit_limit then
      state = get_cpu_state()
      ram = read_ram_hex()
      label_state_hit_count = label_state_hit_count + 1
      label_state_hit_rows[#label_state_hit_rows + 1] = string.format(
        "%04X\t%s\t%d\t%d\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
        rec.addr,
        rec.prg_offset == nil and "unknown" or string.format("%05X", rec.prg_offset),
        rec.count + 1,
        frame,
        fmt_reg(state.pc, 4),
        fmt_reg(state.a, 2),
        fmt_reg(state.x, 2),
        fmt_reg(state.y, 2),
        fmt_reg(state.p, 2),
        fmt_reg(state.s, 2),
        ram)
    end

    if rec.count == 0 then
      rec.state = state or get_cpu_state()
      rec.ram = ram or read_ram_hex()
    end

    rec.count = rec.count + 1
  end)
end

for addr in pairs(labels) do
  register_label(addr)
end

local replay_frames = parse_replay(replay_path)

FCEU.speedmode("maximum")

for i = 1, max_frames do
  frame = i
  joypad.set(1, replay_frames[i] or {})
  FCEU.frameadvance()
end

local rows = {
  "cpu_addr\tprg_offset\tcount\tfirst_frame\trole\n"
}

local keys = {}
for key in pairs(executed) do
  keys[#keys + 1] = key
end
table.sort(keys)

for _, key in ipairs(keys) do
  local rec = executed[key]
  rows[#rows + 1] = string.format(
    "%04X\t%s\t%d\t%d\t%s\n",
    rec.addr,
    rec.prg_offset == nil and "unknown" or string.format("%05X", rec.prg_offset),
    rec.count,
    rec.first_frame,
    rec.role)
end

write_file(out_dir .. "/executed_labels.tsv", table.concat(rows))

local state_rows = {
  "cpu_addr\tprg_offset\tfirst_frame\tpc\ta\tx\ty\tp\ts\tram_0000_07ff\n"
}

for _, key in ipairs(keys) do
  local rec = executed[key]
  state_rows[#state_rows + 1] = string.format(
    "%04X\t%s\t%d\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
    rec.addr,
    rec.prg_offset == nil and "unknown" or string.format("%05X", rec.prg_offset),
    rec.first_frame,
    fmt_reg(rec.state.pc, 4),
    fmt_reg(rec.state.a, 2),
    fmt_reg(rec.state.x, 2),
    fmt_reg(rec.state.y, 2),
    fmt_reg(rec.state.p, 2),
    fmt_reg(rec.state.s, 2),
    rec.ram)
end

write_file(out_dir .. "/label_states.tsv", table.concat(state_rows))
write_file(out_dir .. "/label_state_hits.tsv", table.concat(label_state_hit_rows))

local mapper_rows = {
  "frame\taddr\tvalue\tstate\n"
}
for _, row in ipairs(mapper_writes) do
  mapper_rows[#mapper_rows + 1] = row
end
write_file(out_dir .. "/mapper_writes.tsv", table.concat(mapper_rows))

local apu_rows = {
  "frame\tcycle\taddr\tvalue\n"
}
for _, row in ipairs(apu_writes) do
  apu_rows[#apu_rows + 1] = row
end
write_file(out_dir .. "/apu_writes.tsv", table.concat(apu_rows))

local ppu_rows = {
  "frame\tcycle\taddr\tregister\tvalue\n"
}
for _, row in ipairs(ppu_writes) do
  ppu_rows[#ppu_rows + 1] = row
end
write_file(out_dir .. "/ppu_writes.tsv", table.concat(ppu_rows))

local ppu_vram_rows = {
  "frame\tcycle\taddr\tregion\tvalue\n"
}
for _, row in ipairs(ppu_vram_writes) do
  ppu_vram_rows[#ppu_vram_rows + 1] = row
end
write_file(out_dir .. "/ppu_vram_writes.tsv", table.concat(ppu_vram_rows))

local oam_dma_rows = {
  "frame\tcycle\tpage\tbytes_0000_00ff\n"
}
for _, row in ipairs(oam_dma_writes) do
  oam_dma_rows[#oam_dma_rows + 1] = row
end
write_file(out_dir .. "/oam_dma.tsv", table.concat(oam_dma_rows))

write_file(out_dir .. "/trace_summary.txt", table.concat({
  "emulator=fceux\n",
  "script=tools/fceux_trace.lua\n",
  "labels=", labels_path, "\n",
  "replay=", replay_path or "", "\n",
  "frames=", tostring(max_frames), "\n",
  "registered_label_count=", tostring(label_count), "\n",
  "executed_label_count=", tostring(executed_count), "\n",
  "mapper_write_count=", tostring(mapper_write_count), "\n",
  "apu_write_count=", tostring(apu_write_count), "\n",
  "ppu_write_count=", tostring(ppu_write_count), "\n",
  "ppu_vram_write_count=", tostring(ppu_vram_write_count), "\n",
  "oam_dma_count=", tostring(oam_dma_count), "\n",
  "label_state_count=", tostring(executed_count), "\n",
  "label_state_hit_count=", tostring(label_state_hit_count), "\n",
  "label_state_hit_limit=", tostring(label_state_hit_limit), "\n",
  "complete=1\n",
}))

if done_path and done_path ~= "" then
  write_file(done_path, "complete\n")
end

while true do
  FCEU.frameadvance()
end
